# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion', models.TextField(blank=True, verbose_name='Discussion')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=20)),
                ('Date', models.IntegerField()),
                ('Place', models.CharField(max_length=20)),
                ('Note', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='discussion',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='cms.Schedule', verbose_name='Schedule'),
        ),
    ]
